name: alexnussbaum
favicon: null
layout_spectrum: 0.6013571151997894
typography_spectrum: 0.44776712311431766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1683674391824752
  lightness: 0.7527739412616938
  saturation: 0.3423008194658905
  rhythmicContrast: 0.8835799074731767
purpose: []
